import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import favicon from "./FavIcon1.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shaun Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/FavIcon1.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
