import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import favicon from "./FavIcon1.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shaun Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-6SL2J917ZS"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-6SL2J917ZS');
            `,
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
